### ISSUE TITLE
[frontend] Criar Recuperação de senha

### ISSUE THREAD

**Issue by vinnyfs89** [culturagovbr/comunication-service#109]
Criar funcionalidade para *Recuperação de senha*.
- [ ] Frontend
    - [ ] Criar novo componente Vue - Esqueci minha senha (e-mail ou usuário) -> Enviará mensagem por todas as plataformas cadastradas (Exemplo: whatsapp, email, telegram, etc...) contendo o link com o hash para inserir a nova senha
    - [x] Criar novo componente Vue - Recurar senha. Deve conter os campos *Nova Senha* , *Repetir Nova Senha* e um *botão Salvar*.
    - [x] Utilizar novo componente na tela inicial

**Comment by EnzoAlexsander** [comment]
Componentes de Recuperação e Redefinição de senha criados na branch feature/esqueci-minha-senha
Falta somente a parte do backend.

**Comment by vinnyfs89** [comment]
Item não concluído na Sprint 1. Movendo para Product Backlog.
Caso vá para a próxima Sprint, deve ser reestimado.

**Comment by guiamado** [comment]
Issue resolvida durante o desenvolvimento da issue #120.
