### ISSUE TITLE
[backend] Plataforma - Envio de mensagem por e-mail

### ISSUE THREAD

**Issue by vinnyfs89** [culturagovbr/comunication-service#120]
Criar Plataforma para envio de mensagem por e-mail

**Comment by guiamado** [comment]
- [ ] Enviar email ao criar usuário na parte interna
- [ ] Enviar email ao criar usuario na tela inicial
- [ ] Ao disparar uma notificação informar os vinculados por email

**Comment by vinnyfs89** [comment]
Item não concluído na Sprint 1. 
Movendo para Product Backlog.
Caso vá para a próxima Sprint, deve ser reestimado.

**Comment by guiamado** [comment]
Estou com impedimento de ter acesso ao servidor de email da cultura para fazer os testes externos. Testes realizados com a ferramenta de desenvolvimento MailGun está funcionando OK.

**Comment by guiamado** [comment]
Impedimento Resolvido, feito testes com o email da cultura e funcionando OK.
