### ISSUE TITLE
Transformar webapp em biblioteca

### ISSUE THREAD

**Issue by vinnyfs89** [culturagovbr/comunication-service#220]
Transformar webapp em biblioteca javascript para que possa ser adicionada como dependência em outros projetos que queiram consumir o frontend da aplicação.

**Comment by vinnyfs89** [comment]
Referências: 
- https://medium.freecodecamp.org/how-to-create-and-publish-your-npm-package-node-module-in-just-10-minutes-b8ca3a100050

**Comment by guiamado** [comment]
Segue link que possa ajudar na realização da issue: [vue biblioteca externa](https://br.vuejs.org/v2/cookbook/packaging-sfc-for-npm.html)

**Comment by vinnyfs89** [comment]
Outra referência : https://medium.com/justfrontendthings/how-to-create-and-publish-your-own-vuejs-component-library-on-npm-using-vue-cli-28e60943eed3

**Comment by vinnyfs89** [comment]
https://forum.vuejs.org/t/how-to-create-an-npm-package-of-a-vue-js-project-which-uses-vuex/14706/2
